Thumb: Implement LSL for shift
RIP-Comm/clementine pull request #154
Opened 2022-12-20 16:25 UTC by guerinoni

- CPU: Create `ShifKind` for u32/u16 conversion
- CPU: Move `ArithmeticOpResult` into alu_instruction module
- Thumb: Implement `LSL` for shift register

2022-12-21 11:46 UTC, AlessioC31 requested changes
Since we moved the `shift` logic to a new function, we lose the fact that before the code was modifying the `carry` variable and later changing it in the cpu. Now the `shift` function doesn't change the carry, thus the `shift_operand` function doesn't updates the `carry` bit in the cpsr.

I'm not sure about using `ArithmeticOpResult` here since it contains fields we would never use in such a context. Maybe we can rethink it?

2022-12-21 11:46 UTC, AlessioC31 commented on emu/src/cpu/alu_instruction.rs
> +pub fn shitf(kind: ShiftKind, shift_amount: u32, rm: u32, _carry: bool) -> ArithmeticOpResult {
`shift`?

2022-12-21 17:52 UTC, guerinoni commented on emu/src/cpu/alu_instruction.rs
> +pub fn shitf(kind: ShiftKind, shift_amount: u32, rm: u32, _carry: bool) -> ArithmeticOpResult {
Lol

2022-12-21 18:23 UTC, guerinoni commented
> Since we moved the `shift` logic to a new function, we lose the fact that before the code was modifying the `carry` variable and later changing it in the cpu. Now the `shift` function doesn't change the carry, thus the `shift_operand` function doesn't updates the `carry` bit in the cpsr, since it only uses the `result` field of the returned value from `shift`
> 
> I'm not sure about using `ArithmeticOpResult` here since it contains fields we would never use in such a context. The idea behind this struct was to carry the "new state" of an ALU operation (add/sub). Maybe we can rethink it? Maybe we could make it more "modular"

Ok now I re-designed a little bit and seems correct to me! Obviously the refactor will be nicer when all operation will be split as I did for `shift`... But meanwhile... :)

2022-12-22 10:33 UTC, AlessioC31 reviewed
I still think tha `ArithmeticOpResult` doesn't fit here 100% but we can first merge this and maybe in another PR we can rethink this entire thing

2022-12-22 10:46 UTC, guerinoni commented on emu/src/cpu/alu_instruction.rs
> +                    ..Default::default()
Oh yes! Nice catch

2022-12-23 07:58 UTC, AlessioC31 approved these changes

2022-12-23 14:44 UTC, merged