Add bit manipulation methods
RIP-Comm/clementine pull request #39
Opened 2022-09-08 23:38 UTC by simo498

It adds some methods to check and set single bits. For now there aren't methots to handle multiple bits masks, and it's limited to u32 (due to the assence of a common Integer trait  in rust).

Refers to #33

2022-09-09 20:11 UTC, simo498 commented
> @simo498 here I appreciate more feedback also from @AlessandroGrassi99 and @gallottino 
> But sure I prefer this kind of api not for a struct `Bitwise` but as implementation of `u32` or such... In this way you can do `my_number.toggle_bit(15)` and this will toggle the bit 15.
> I have some doubt also if is better `is_set/is_reset` but let's discuss :D

Yeah it's an idea. Another is to create a wrapper like ’Bitwise(u32)’. Anyway let's hear the opinion of other people on which implementation we should uses. I also think something more direct like u32::get_bit or whatever would be more readable

2022-09-10 12:36 UTC, gallottino requested changes
I also like that you create a struct from u32 and use it to manipulate the inside values. If you can change it will be great. u32 as parameter in every function is a bit redundant and also less readable. Be careful to test every function with at least an atomic test.

2022-09-10 12:36 UTC, gallottino commented on src/bitwise.rs
> +    fn basic_tests() {
Here I prefer to split  the tests to recognize faster a future change that broke this implementation.  You can also take this test with all implementations, but I think  also it is better to have almost one test for every functionality.

2022-09-10 17:30 UTC, simo498 commented
I implemented the methods to u32 directly, so they can be called by just adding `use crate::bitwise::Bits`, i also added `rand` for testing, but it can be useful in the future as well

2022-09-10 18:11 UTC, gallottino approved these changes

2022-09-10 22:28 UTC, guerinoni requested changes
Looks nicer :)

2022-09-10 22:28 UTC, guerinoni commented on Cargo.toml
> +rand = "0.8.5"
Can you move this as dev-dependencies?

2022-09-11 01:13 UTC, simo498 commented on Cargo.toml
> +rand = "0.8.5"
Sure

2022-09-11 09:37 UTC, guerinoni approved these changes
Good :)

2022-09-11 09:37 UTC, merged